version: '3.5'

services:
  node-api:
    container_name: dog-walkers-app
    restart: always
    ports:
      - "3000:3000"
    image: dog-walkers-node-js
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=docker
    command: "npm start"
    networks:
      - tpo-network
  mongo-db:
    image: mongo
    container_name: dog-walkers-mongodb
    ports:
      - "27017-27019:27017-27019"
    networks:
      - tpo-network
networks:
  tpo-network:
    name: tpo-network
    driver: bridge